syntax = "proto3";
package invoice;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Invoice {
    int32 id = 1;
    int32 invoice_number = 2;
    string starting_date = 3;  // Using string for date
    string ending_date = 4;    // Using string for date
    string sender_info = 5;
    double subtotal = 6;       // Using double for numeric
    string payment_instructions = 7;
    string notes = 8;
    int32 currency_id = 9;
    int32 incoterms_id = 10;
}

// POST message
message CreateInvoiceRequest {
    int32 invoice_number = 1;
    string starting_date = 2;
    string ending_date = 3;
    string sender_info = 4;
    double subtotal = 5;
    string payment_instructions = 6;
    string notes = 7;
    int32 currency_id = 8;
    int32 incoterms_id = 9;
}

message CreateInvoiceResponse {
    Invoice invoice = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetInvoiceRequest {
    int32 id = 1;
}

message GetInvoiceResponse {
    Invoice invoice = 1;
    bool success = 2;
    string message = 3;
}

message ListInvoicesRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListInvoicesResponse {
    repeated Invoice invoices = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateInvoiceRequest {
    int32 id = 1;
    int32 invoice_number = 2;
    string starting_date = 3;
    string ending_date = 4;
    string sender_info = 5;
    double subtotal = 6;
    string payment_instructions = 7;
    string notes = 8;
    int32 currency_id = 9;
    int32 incoterms_id = 10;
}

message UpdateInvoiceResponse {
    Invoice invoice = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteInvoiceRequest {
    int32 id = 1;
}

message DeleteInvoiceResponse {
    bool success = 1;
    string message = 2;
}