syntax = "proto3";
package company_user;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message CompanyUser {
    int32 id = 1;
    int32 user_id = 2;
    int32 company_id = 3;
}

// POST message
message CreateCompanyUserRequest {
    int32 user_id = 1;
    int32 company_id = 2;
}

message CreateCompanyUserResponse {
    CompanyUser company_user = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetCompanyUserRequest {
    int32 id = 1;
}

message GetCompanyUserResponse {
    CompanyUser company_user = 1;
    bool success = 2;
    string message = 3;
}

message ListCompanyUsersRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListCompanyUsersResponse {
    repeated CompanyUser company_users = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateCompanyUserRequest {
    int32 id = 1;
    int32 user_id = 2;
    int32 company_id = 3;
}

message UpdateCompanyUserResponse {
    CompanyUser company_user = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteCompanyUserRequest {
    int32 id = 1;
}

message DeleteCompanyUserResponse {
    bool success = 1;
    string message = 2;
}