syntax = "proto3";
package models.finace.transaction.check ;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Check {
    int32 id = 1;
    int32 account_id = 2;
    int32 currency_id = 3;
    double amount = 4;  // Using double for numeric
}

// POST message
message CreateCheckRequest {
    int32 account_id = 1;
    int32 currency_id = 2;
    double amount = 3;
}

message CreateCheckResponse {
    Check check = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetCheckRequest {
    int32 id = 1;
}

message GetCheckResponse {
    Check check = 1;
    bool success = 2;
    string message = 3;
}

message ListChecksRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListChecksResponse {
    repeated Check checks = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateCheckRequest {
    int32 id = 1;
    int32 account_id = 2;
    int32 currency_id = 3;
    double amount = 4;
}

message UpdateCheckResponse {
    Check check = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteCheckRequest {
    int32 id = 1;
}

message DeleteCheckResponse {
    bool success = 1;
    string message = 2;
}