syntax = "proto3";
package models.account.core.account_details;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message AccountDetail {
    int32 id = 1;
    int32 account_id = 2;
    string bank_name = 3;
    string branch_name = 4;
    string swift_code = 5;
    string ifsc_code = 6;
    string routing_number = 7;
    string iban = 8;
    string bank_website = 9;
}

// POST message
message CreateAccountDetailRequest {
    int32 account_id = 1;
    string bank_name = 2;
    string branch_name = 3;
    string swift_code = 4;
    string ifsc_code = 5;
    string routing_number = 6;
    string iban = 7;
    string bank_website = 8;
}

message CreateAccountDetailResponse {
    AccountDetail account_detail = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetAccountDetailRequest {
    int32 id = 1;
}

message GetAccountDetailResponse {
    AccountDetail account_detail = 1;
    bool success = 2;
    string message = 3;
}

message ListAccountDetailsRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListAccountDetailsResponse {
    repeated AccountDetail account_details = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateAccountDetailRequest {
    int32 id = 1;
    int32 account_id = 2;
    string bank_name = 3;
    string branch_name = 4;
    string swift_code = 5;
    string ifsc_code = 6;
    string routing_number = 7;
    string iban = 8;
    string bank_website = 9;
}

message UpdateAccountDetailResponse {
    AccountDetail account_detail = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteAccountDetailRequest {
    int32 id = 1;
}

message DeleteAccountDetailResponse {
    bool success = 1;
    string message = 2;
}