syntax = "proto3";
package payment;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Payment {
    int32 id = 1;
    int32 company_id = 2;
    int32 currency_id = 3;
    double amount = 4;  // Using double for numeric
}

// POST message
message CreatePaymentRequest {
    int32 company_id = 1;
    int32 currency_id = 2;
    double amount = 3;
}

message CreatePaymentResponse {
    Payment payment = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetPaymentRequest {
    int32 id = 1;
}

message GetPaymentResponse {
    Payment payment = 1;
    bool success = 2;
    string message = 3;
}

message ListPaymentsRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListPaymentsResponse {
    repeated Payment payments = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdatePaymentRequest {
    int32 id = 1;
    int32 company_id = 2;
    int32 currency_id = 3;
    double amount = 4;
}

message UpdatePaymentResponse {
    Payment payment = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeletePaymentRequest {
    int32 id = 1;
}

message DeletePaymentResponse {
    bool success = 1;
    string message = 2;
}