syntax = "proto3";

package company;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Company {
    int32 id = 1;
    string email_address = 2;
    string name = 3;
    string timestamp = 4;  // Using string for date
}

// POST message
message CreateCompanyRequest {
    string email_address = 1;
    string name = 2;
    string timestamp = 3;
}

message CreateCompanyResponse {
    Company company = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetCompanyRequest {
    oneof identifier {
        int32 id = 1;
        string email_address = 2;
        string name = 3;
        string timestamp = 4; 
    }
}

message GetCompanyResponse {
    Company company = 1;
    bool success = 2;
    string message = 3;
}

message ListCompaniesRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListCompaniesResponse {
    repeated Company companies = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateCompanyRequest {
    int32 id = 1;
    string email_address = 2;
    string name = 3;
    string timestamp = 4;
}

message UpdateCompanyResponse {
    Company company = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteCompanyRequest {
    int32 id = 1;
}

message DeleteCompanyResponse {
    bool success = 1;
    string message = 2;
}