version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ~/finance/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=finance_user
      - POSTGRES_DB=finance_DB
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  postgrest:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://finance_user:S3cret@db:5432/finance_DB
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: finance_user
    ports:
      - "3000:3000"
    depends_on:
      - db
