[package]
name = "server"
version = "0.1.1"
edition = "2024"
build = "build.rs"


[dependencies]
prost = "0.13.5"
tonic = "0.12.3"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.12.3"
sqlx = "0.8.3"

[build-dependencies]
tonic-build = "0.12.3"
