syntax = "proto3";
import "finance-protobuf/protobuf/models/account/payable_receivable/account_receivable_customer.proto";
package functions.account.payable_receivable.account_receivable_customer;

service AccountReceivableCustomerService {
  rpc CreateAccountReceivableCustomer(models.account.payable_receivable.account_receivable_customer.CreateAccountReceivableCustomerRequest) returns (models.account.payable_receivable.account_receivable_customer.CreateAccountReceivableCustomerResponse);
  rpc GetAccountReceivableCustomer(models.account.payable_receivable.account_receivable_customer.GetAccountReceivableCustomerRequest) returns (models.account.payable_receivable.account_receivable_customer.GetAccountReceivableCustomerResponse);
  rpc ListAccountReceivableCustomers(models.account.payable_receivable.account_receivable_customer.ListAccountReceivableCustomersRequest) returns (models.account.payable_receivable.account_receivable_customer.ListAccountReceivableCustomersResponse);
  rpc UpdateAccountReceivableCustomer(models.account.payable_receivable.account_receivable_customer.UpdateAccountReceivableCustomerRequest) returns (models.account.payable_receivable.account_receivable_customer.UpdateAccountReceivableCustomerResponse);
  rpc DeleteAccountReceivableCustomer(models.account.payable_receivable.account_receivable_customer.DeleteAccountReceivableCustomerRequest) returns (models.account.payable_receivable.account_receivable_customer.DeleteAccountReceivableCustomerResponse);
}