syntax = "proto3";
package tax_money;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message TaxMoney {
    int32 id = 1;
    int32 tax_id = 2;
    int32 money_id = 3;
    string money_type = 4;  // Using string for bpchar
}

// POST message
message CreateTaxMoneyRequest {
    int32 tax_id = 1;
    int32 money_id = 2;
    string money_type = 3;
}

message CreateTaxMoneyResponse {
    TaxMoney tax_money = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetTaxMoneyRequest {
    int32 id = 1;
}

message GetTaxMoneyResponse {
    TaxMoney tax_money = 1;
    bool success = 2;
    string message = 3;
}

message ListTaxMoniesRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListTaxMoniesResponse {
    repeated TaxMoney tax_monies = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateTaxMoneyRequest {
    int32 id = 1;
    int32 tax_id = 2;
    int32 money_id = 3;
    string money_type = 4;
}

message UpdateTaxMoneyResponse {
    TaxMoney tax_money = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteTaxMoneyRequest {
    int32 id = 1;
}

message DeleteTaxMoneyResponse {
    bool success = 1;
    string message = 2;
}