syntax = "proto3";
package models.relationship.company.office ;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Office {
    int32 id = 1;
    int32 company_id = 2;
}

// POST message
message CreateOfficeRequest {
    int32 company_id = 1;
}

message CreateOfficeResponse {
    Office office = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetOfficeRequest {
    int32 id = 1;
}

message GetOfficeResponse {
    Office office = 1;
    bool success = 2;
    string message = 3;
}

message ListOfficesRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListOfficesResponse {
    repeated Office offices = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateOfficeRequest {
    int32 id = 1;
    int32 company_id = 2;
}

message UpdateOfficeResponse {
    Office office = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteOfficeRequest {
    int32 id = 1;
}

message DeleteOfficeResponse {
    bool success = 1;
    string message = 2;
}