syntax = "proto3";
package permission;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message Permission {
    int32 id = 1;
    string description = 2;
    string name = 3;
}

// POST message
message CreatePermissionRequest {
    string description = 1;
    string name = 2;
}

message CreatePermissionResponse {
    Permission permission = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetPermissionRequest {
    int32 id = 1;
}

message GetPermissionResponse {
    Permission permission = 1;
    bool success = 2;
    string message = 3;
}

message ListPermissionsRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListPermissionsResponse {
    repeated Permission permissions = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdatePermissionRequest {
    int32 id = 1;
    string description = 2;
    string name = 3;
}

message UpdatePermissionResponse {
    Permission permission = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeletePermissionRequest {
    int32 id = 1;
}

message DeletePermissionResponse {
    bool success = 1;
    string message = 2;
}