syntax = "proto3";
package account_receivable_customer;

message Filter {
    string field = 1;
    string operator = 2;
    string value = 3;
}

message Sorting {
    string field = 1;
    bool ascending = 2;
}

// core message
message AccountReceivableCustomer {
    int32 id = 1;
    int32 account_receivable_id = 2;
    int32 customer_id = 3;
}

// POST message
message CreateAccountReceivableCustomerRequest {
    int32 account_receivable_id = 1;
    int32 customer_id = 2;
}

message CreateAccountReceivableCustomerResponse {
    AccountReceivableCustomer account_receivable_customer = 1;
    bool success = 2;
    string message = 3;
}

// READ message
message GetAccountReceivableCustomerRequest {
    int32 id = 1;
}

message GetAccountReceivableCustomerResponse {
    AccountReceivableCustomer account_receivable_customer = 1;
    bool success = 2;
    string message = 3;
}

message ListAccountReceivableCustomersRequest {
    int32 page = 1;
    int32 page_size = 2;
    repeated Filter filter = 4;
    int32 offset = 5;
    int32 limit = 6;
    Sorting sort = 7;
}

message ListAccountReceivableCustomersResponse {
    repeated AccountReceivableCustomer account_receivable_customers = 1;
    int32 total_count = 2;
    bool success = 3;
    string message = 4;
}

// UPDATE message
message UpdateAccountReceivableCustomerRequest {
    int32 id = 1;
    int32 account_receivable_id = 2;
    int32 customer_id = 3;
}

message UpdateAccountReceivableCustomerResponse {
    AccountReceivableCustomer account_receivable_customer = 1;
    bool success = 2;
    string message = 3;
}

// DELETE message
message DeleteAccountReceivableCustomerRequest {
    int32 id = 1;
}

message DeleteAccountReceivableCustomerResponse {
    bool success = 1;
    string message = 2;
}